// <auto-generated />
using EliteCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EliteCore.Migrations
{
    [DbContext(typeof(EliteDbContext))]
    [Migration("20250204171815_telefonEklendi")]
    partial class telefonEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EliteCore.Models.GelenMail", b =>
                {
                    b.Property<int>("GelenMailKod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GelenMailKod"));

                    b.Property<string>("Ad")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("GelenMesaj")
                        .HasColumnType("VARCHAR(1000)");

                    b.Property<string>("KullaniciMail")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Soyad")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("GelenMailKod");

                    b.HasIndex("GelenMailKod")
                        .IsUnique();

                    b.ToTable("GelenMailler");
                });
#pragma warning restore 612, 618
        }
    }
}
